defaults: &defaults
  adapter: postgresql
  host: localhost
  encoding: utf8

development:
  database: ruby_performance_development
  <<: *defaults

production:
  database: ruby_performance_development
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>  
  <<: *defaults

staging:
  database: ruby_performance_development
  <<: *defaults

test:
  database: ruby_performance_test
  <<: *defaults
